name: ShowItem
version: '${project.version}'
main: com.github.firewolf8385.showitem.ShowItemPlugin
api-version: 1.13
authors: [firewolf8385]
description: Announce in chat what item a player is holding!
depend: [PlaceholderAPI]
softdepend: [BetterReload]

commands:
  showitem:
    description: Announce the currently held item in chat.
    aliases: [showhand]
  showhelmet:
    description: Show the currently worn helmet in chat.
    aliases: [showhat]
  showchestplate:
    description: Show the currently worn chestplate in chat.
    aliases: [showshirt]
  showleggings:
    description: Show the currently worn leggings in chat.
    aliases: [showpants]
  showboots:
    description: Show the currently worn boots in chat.
    aliases: [showshoes]